# Generated by Django 5.2.6 on 2025-10-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=72),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=72),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
