# Generated by Django 5.2.6 on 2025-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
