# Generated by Django 5.2.6 on 2025-10-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='common.productcolorimage'),
        ),
    ]
